[package]
name = "game_testing"
version = "0.1.0"
authors = ["CyberWolf37 <borel.loic.37@gmail.com>"]
edition = "2018"

[dependencies.amethyst]
version = "0.15"
features = ["vulkan"]

[dependencies]
log = "0.4"
chrono = "0.4.19"
serde = "1.0.117"
ron = "0.6.2"